
[settings]
	#Percentage of players required to trigger a successful sleep.
	#Range: 0 ~ 100
	SleeperPerc = 25
	#Enable alerts
	AlertEnabled = true
	#Text used to alert players that someone is trying to sleep
	OnSleepText = "is now in bed."
	#Text used to alert players that someone stopped trying to sleep
	OnWakeText = "got out of bed."
	#Text to alert the server that sleeping was successful
	OnMorningText = "The night has passed."
	#Include miners in player calculations
	IncludeMiners = false
	#Players below this Y level will be counted as miners
	#Range: 1 ~ 255
	GroundLevel = 60
	#Allow players to set their spawn point using a bed during the day
	AllowSetSpawnDaytime = true

