placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
#Unavailable if TerraForged mod installed
snowAccumulationDuringSnowstorm = false
#Unavailable if TerraForged mod installed
snowAccumulationDuringSnowfall = false
#9 = Unlimited
#Range: 1 ~ 9
snowAccumulationMaxLayers = 9
#Unavailable if TerraForged mod installed
thinnerBoundingBox = false
snowMakingIce = true
snowOnIce = false
snowNeverMelt = false
snowMeltsInWarmBiomes = true
#Should snow melt if layers are more than 1
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
#If you want to uninstall this mod, you probably want to make snow-covered blocks back to normal via random tick.
retainOriginalBlocks = false
advancedBlockInteraction = false

